# Generated by Django 5.0.6 on 2024-05-27 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_likedpost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.ManyToManyField(
                through="post.LikedPost", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
