# Generated by Django 5.0.6 on 2024-05-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_sockets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("online", "Online"), ("offline", "Offline")],
                default="offline",
                max_length=20,
            ),
        ),
    ]
